stages: 
  - build
  - deploy

build-petclinic:
  stage: build
  script:
    - echo "Building Petclinic with Maven"
    - mvn clean package

deploy-to-tomcat:
  stage: deploy
  script:
    - echo "Deploying to Tomcat"
    - systemctl start tomcat
    - mvn tomcat9:deploy
    - echo "Done deploying"
