name: Build and Deploy Petclinic

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: List WAR files (debug)
        run: ls -lh target/

      - name: Start Tomcat Server
        run: |
          echo "Starting Tomcat..."
          sudo /usr/bin/systemctl start tomcat
          sleep 10

      - name: Deploy WAR to Tomcat
        run: |
          echo "Deploying WAR to Tomcat..."
          curl -v -u "$TOMCAT_USER:$TOMCAT_PASS" \
               -T "$WAR" \
               "$URL"
        env:
          WAR: target/petclinic.war
          URL: ${{ secrets.TOMCAT_HOST }}/manager/text/deploy?path=/petclinic&update=true
          TOMCAT_USER: ${{ secrets.TOMCAT_USER }}
          TOMCAT_PASS: ${{ secrets.TOMCAT_PASS }}

